# theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes"
title: VR Storm Lab
description: Universal character model viewer and motion player 
google_analytics: UA-147265380-2
include: app-ads.txt
logo: /images/icon.png
breadcrumbs: false
url: https://vrstormlab.com/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-3717TSDBXS"
    anonymize_ip: false # default

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
