# theme: jekyll-theme-slate
remote_theme: "alloystorm/minimal-mistakes"
title: VR Storm Lab
description: Universal character model viewer and motion player 
google_analytics: UA-147265380-2
include: app-ads.txt
logo: /images/icon.png
breadcrumbs: false
url: https://vrstormlab.com/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-3717TSDBXS"
    anonymize_ip: false # default

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

footer:
  links:
    - label: "Patreon"
      icon: "fab fa-patreon"
      url: "https://www.patreon.com/dvvr"
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.gg/wCMy7C3H"
    - label: "Steam"
      icon: "fab fa-steam"
      url: "https://store.steampowered.com/search/?developer=VR%20Storm%20Lab"
    - label: "Itch.io"
      icon: "fab fa-itch-io"
      url: "https://stormlab.itch.io"
    - label: "Google Play"
      icon: "fab fa-google-play"
      url: "https://play.google.com/store/apps/details?id=com.vrstormlab.dancexr"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/@dancexr"
    - label: "TikTok"
      icon: "fab fa-tiktok"
      url: "https://www.tiktok.com/@vrstormlab"  
    - label: "BiliBili"
      icon: "fas fa-play-circle"
      url: "https://space.bilibili.com/167383940"
    - label: "iXiGua"
      icon: "fas fa-play-circle"
      url: "https://www.ixigua.com/home/633750488883656"      